runtime: ruby32
entrypoint: bundle exec rails server -p $PORT

env_variables:
  RAILS_ENV: "production"
  RAILS_MASTER_KEY: "your_master_key_here"
  DATABASE_URL: "postgresql://username:password@/database_name?host=/cloudsql/your-project:region:instance-name"

beta_settings:
  cloud_sql_instances: "your-project:region:instance-name" 